apiVersion: v1
kind: Secret
metadata:
  name: elastic-basic-auth
  namespace: gold-dev
type: Opaque
stringData:
  ELASTIC_USER: "elastic"
  ELASTIC_PASS: "Tuananh123."
  ELASTIC_HOSTS: "https://192.168.31.156:9200"


