apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: logging
  labels:
    app: fluent-bit
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020

    @INCLUDE input-kubernetes.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE output-elasticsearch.conf

  input-kubernetes.conf: |
    [INPUT]
        Name              tail
        Path              /var/log/containers/*.log
        Parser            cri
        Tag               kube.*
        Refresh_Interval  5
        Mem_Buf_Limit     50MB
        Skip_Long_Lines   On
        Skip_Empty_Lines  On

  filter-kubernetes.conf: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log            On
        Merge_Log_Key        log
        Keep_Log             Off
        K8S-Logging.Parser   On
        K8S-Logging.Exclude  Off
        Annotations          Off
        Labels               On

    [FILTER]
        Name                modify
        Match               kube.*
        Add                 ENV ${ENV}
        Add                 APP ${APP}

    [FILTER]
        Name                nest
        Match               kube.*
        Operation           lift
        Nested_under         kubernetes
        Add_prefix           k8s_

    [FILTER]
        Name                record_modifier
        Match               kube.*
        Record              cluster_name minikube

  output-elasticsearch.conf: |
    [OUTPUT]
        Name            es
        Match           kube.*
        Host            ${ES_HOST}
        Port            9200
        HTTP_User       ${ES_USER}
        HTTP_Passwd     ${ES_PASS}
        Logstash_Format On
        Replace_Dots    On
        Suppress_Type_Name On
        Retry_Limit     10
        Index           logs-${ENV:-dev}-%Y.%m.%d
        Type            _doc
        tls             On
        tls.verify      Off

  parsers.conf: |
    [PARSER]
        Name        cri
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On

