apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gold-dev
resources:
  - namespace.yaml
  - postgres-secret.yaml
  - postgres-statefulset.yaml
  - postgres-service.yaml
  - api-deployment.yaml
  - api-service.yaml
  - ui-deployment.yaml
  - ui-service.yaml
  - flyway-job.yaml
  - cron-scrape-doji.yaml
  - cron-snapshot-daily.yaml
  - configmap-app.yaml

