apiVersion: apps/v1
kind: Deployment
metadata:
  name: gold-tracker-api
spec:
  template:
    spec:
      containers:
        - name: api
          env:
            - name: SCRAPER_ENABLED
              value: "true"   # enable if you want hosted service too
            - name: SNAPSHOT_ENABLED
              value: "false"

